---
stages:
  - prepare
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip"
  GIT_STRATEGY: clone

cache:
    paths:
    - .pip/
    - .env/

init:
  stage: prepare
  tags:
    - k3s
  script:
    - pip3 install virtualenv
    - python3 -m virtualenv .env
    - source .env/bin/activate
    - pip install -r requirements.txt
    # - ansible-galaxy install -r requirements.yml -f
    - python -V
    - pip -V
    - ansible --version
    - molecule --version
    - docker --version

molecule:
  stage: test
  tags:
    - k3s
  script:
    - source .env/bin/activate
    - molecule test -s arm64
...
