---

- name: Check for gitlab-runner binary
  stat:
    path:  /usr/local/bin/gitlab-runner
  register: gitlab_runner_binary

- name: Download latest gitlab-runner
  get_url:
    url: "https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-{{ architecture }}"
    dest: /tmp/gitlab-runner
    mode: '0777'

- name: Get checksum for latest git-labrunner
  stat:
    path: /tmp/gitlab-runner
    get_checksum: yes
  register: latest_gitlab_runner_binary

- name: Get checksum for current git-labrunner
  stat:
    path: /usr/local/bin/gitlab-runner
    get_checksum: yes
  register: current_gitlab_runner_binary

- name: Stop gitlab-runner
  command: gitlab-runner stop
  when:
    - gitlab_runner_binary.stat.exists
    - current_gitlab_runner_binary.stat.checksum != latest_gitlab_runner_binary.stat.checksum

- name: Copy gitlab-runner binary to /usr/local/bin
  copy:
    src: /tmp/gitlab-runner
    dest: /usr/local/bin/gitlab-runner
    mode: "0777"
    remote_src: yes
  when:
    - not gitlab_runner_binary.stat.exists
    - current_gitlab_runner_binary.stat.checksum != latest_gitlab_runner_binary.stat.checksum

- name: Add the user 'gitlab-runner' with a bash shell
  user:
    name: gitlab-runner
    create_home: true
    comment: GitLab Runner
    shell: /bin/bash
    groups: "{{ gitlab_runner_groups }}"
    append: yes

# required for shell executor on systems with .bash_logout
# https://gitlab.com/gitlab-org/gitlab-runner/-/issues/26605#note_403531095
- name: Remove .bash_logout from gitlab-runner user
  file:
    path: ~/.bash_logout
    mode: "0000"
    state: abesent
  become: true
  become_user: gitlab-runner

- name: Install gitlab-runner
  command: gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner
  register: gitlab_runner_install
  failed_when:
    - gitlab_runner_install.rc != 0
    - "'FATAL: Failed to install gitlab-runner: Init already exists: /etc/systemd/system/gitlab-runner.service' not in gitlab_runner_install.stderr"
  changed_when:
    - "'FATAL: Failed to install gitlab-runner: Init already exists: /etc/systemd/system/gitlab-runner.service' not in gitlab_runner_install.stderr"

- name: Start gitlab-runner
  command: gitlab-runner start
  when:
    - not gitlab_runner_binary.stat.exists
    - current_gitlab_runner_binary.stat.checksum != latest_gitlab_runner_binary.stat.checksum

...