---

- name: Check for gitlab-runner binary
  stat:
    path:  /usr/local/bin/gitlab-runner
  register: gitlab_runner_binary

- name: Stop gitlab-runner
  command: gitlab-runner stop
  when: gitlab_runner_binary.stat.exists

- name: Download gitlab-runner
  get_url:
    url: "https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-{{ architecture }}"
    dest: /usr/local/bin/gitlab-runner
    mode: '0777'

- name: Add the user 'gitlab-runner' with a bash shell
  user:
    name: gitlab-runner
    create_home: true
    comment: GitLab Runner
    shell: /bin/bash
    groups: "{{ gitlab_runner_groups }}"
    append: yes

- name: Install gitlab-runner
  command: gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner
  register: gitlab_runner_install
  failed_when:
    - gitlab_runner_install.rc != 0
    - "'FATAL: Failed to install gitlab-runner: Init already exists: /etc/systemd/system/gitlab-runner.service' not in gitlab_runner_install.stderr"
    
- name: Start gitlab-runner
  command: gitlab-runner start
  
...