---
  dependency:
    name: galaxy
  driver:
    name: docker
  platforms:
    - name: instance
      image: centos:8
      command: /sbin/init
      privileged: yes
      tmpfs:
        - /run
        - /tmp
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
  provisioner:
    name: ansible
  verifier:
    name: ansible
  lint: |
    set -e
    ansible-lint .
...