---
  dependency:
    name: galaxy
  driver:
    name: docker
  platforms:
    - name: instance
      image: centos:8
  provisioner:
    name: ansible
  verifier:
    name: ansible
  lint: |
    set -e
    ansible-lint .
...